# -*- coding: utf-8 -*-
"""LinearAlgebra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m378spUCvmfvU1k91QIWBYaAhAoraNqb
"""

import numpy as np

A = np.array([
    [0.65, 0.10, 0.25, 0.00],
    [0.30, 0.10, 0.35, 0.25],
    [0.30, 0.15, 0.15, 0.40],
    [0.20, 0.10, 0.30, 0.40]
])

I = np.eye(4)
IA_Difference = I - A

b = np.zeros(4)
# Use numpy's linear algebra solver to find equilibrium prices
prices = np.linalg.solve(IA_Difference, b)
labels = ["Agriculture", "Energy", "Manufacturing", "Transportation"]
for i in range(4):
    price = prices[i]
    print(f"{labels[i]}: {price}")

